lastone/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^notes/', include('notes.urls')),

]

notes/urls.py

from django.conf.urls import url, include
from . import views
from notes.views import MovieList, NoteList, CalendarList

app_name = 'notes'

urlpatterns = [
    url(r'^movies/$', MovieList.as_view()),
    url(r'^notes/$', NoteList.as_view()),
    url(r'^calendar/$', CalendarList.as_view()),
    url(r'^calendar/add/$', views.CalendarCreate.as_view(), name='calendar-add'),

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'movies/add/$', views.MovieCreate.as_view(), name='movie-add'),
    url(r'notes/add/$', views.NoteCreate.as_view(), name='note-add'),
    url(r'movies/(?P<pk>[0-9]+)/$', views.MovieUpdate.as_view(), name='movie-update'),
        # music/album/2/delete
    url(r'movies/(?P<pk>[0-9]+)/delete/$', views.MovieDelete.as_view(), name='movie-delete'),

]

notes/models.py
from django.db import models
from django.utils import timezone

now = timezone.now()
class Category(models.Model):
    name = models.CharField(max_length=200)

class Note(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    categories = models.ManyToManyField(Category)

class Movie(models.Model):
    name = models.CharField(max_length=300)
    release_date = models.DateTimeField(blank=True, null=True)
    imdb_link = models.CharField(max_length=500)
    categories = models.ManyToManyField(Category)

    def remaining_time(self):
        remaining_time = timezone.now().date()-self.release_date.date()
        return str(remaining_time)

    def name_plus(self):
        nam = self.name +"love"
        return nam

class News(models.Model):
    title = models.CharField(max_length=300)
    body = models.TextField()
    site = models.CharField(max_length=500)
    categories = models.ManyToManyField(Category)

class Calendar(models.Model):
    title = models.CharField(max_length=300)
    date_when = models.DateTimeField(blank=True, null=True)

notes/forms.py
from django.forms import ModelForm, Textarea, URLField, SelectDateWidget, SplitHiddenDateTimeWidget
from django.forms.extras.widgets import SelectDateWidget
from .models import Movie, Note, Calendar
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.admin.widgets import AdminDateWidget

class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'release_date', 'imdb_link', 'categories']
        widgets = {
            'release_date': SelectDateWidget,
        }

class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'body', 'created_at', 'categories']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),

        }

class CalendarForm(ModelForm):
    class Meta:
        model = Calendar
        fields = ['title', 'date_when']
        widgets = {
            'date_when': SelectDateWidget,
        }


notes/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Movie, Note, News, Calendar, Category
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import NoteForm, MovieForm, CalendarForm


class MovieList(ListView):
    template_name = 'notes/movie_list.html'
    queryset = Movie.objects.order_by('release_date')
    context_object_name = 'all_movies'

class NoteList(ListView):
    template_name = 'notes/note_list.html'
    queryset = Note.objects.all()
    context_object_name = 'all_notes'



class NewsList(ListView):
    model = News

class CalendarList(ListView):
    model = Calendar
    queryset = Calendar.objects.order_by("date_when")
    context_object_name = 'all_calendar'

class IndexView(ListView):
    template_name = 'notes/index.html'
    context_object_name = 'all_movies'
    queryset = Movie.objects.order_by('release_date')

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['all_notes'] = Note.objects.all()
        context['all_calendar'] = Calendar.objects.all()
        # And so on for more models
        return context


class NoteCreate(CreateView):
    form_class = NoteForm
    template_name = 'notes/note_form.html'
    success_url = reverse_lazy('notes:index')


class MovieCreate(CreateView):
    form_class = MovieForm
    template_name = 'notes/movie_form.html'
    success_url = reverse_lazy('notes:index')

class MovieUpdate(UpdateView):
    model = Movie
    fields = ['name', 'release_date', 'imdb_link', 'categories']

class MovieDelete(DeleteView):
    model = Movie
    success_url = reverse_lazy('notes:index')

class CalendarCreate(CreateView):
    form_class = CalendarForm
    template_name = 'notes/calendar_form.html'
    success_url = reverse_lazy('notes:index')

notes/templates/notes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Note App{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

notes/templates/notes/calendar_form.html
{% extends 'notes/base.html' %}
{% block body %}
    <h2>New Calendar Object</h2>
    <form  action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'notes/form-template.html' %}
        <br><br><br><br><br>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
{% endblock %}

notes/templates/notes/calendar_list.html
{% extends 'notes/base.html' %}

{% block body %}
    <h3>Calendar Objects</h3>
   <ul>
        {% for m in all_calendar %}
            <li>
                <h4> {{ m.title }}</h4>
            <p>When: {{ m.date_when }}</p>

            <br>
        {% endfor %}

    </ul>
{% endblock %}

notes/templates/notes/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-12 col-sm-10">
            <span class="text-danger small">{{ field.error }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

notes/templates/notes/home.html
{% extends 'notes/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="jumbotron">
            <h1>Hello</h1>
            <p>You are on your Dashboard</p>
        </div>
    </div>
</div>
{% endblock %}

notes/templates/notes/index.html
{% extends 'notes/base.html' %}


{% block body %}




    <div id="container">
        <div class="colM col-md-5">
            <ul>
            <li><p><a href="/notes/movies/add">Add new movie</a></p>
        {% include "notes/movie_list.html" %}</li><br>
             <li>
              <p><a href="/notes/calendar/add">Add new Calendar Object</a></p>
               {% include "notes/calendar_list.html" %}

             </li><br>
            <li>
              <p><a href="/notes/notes/add">Add new note</a></p>
               {% include "notes/note_list.html" %}

            </li></ul>
        </div>
    </div>

{% endblock %}


notes/templates/notes/login.html
{% extends 'notes/base.html' %}


{% block content %}
    {% if form.errors %}

<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}

<p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}

<p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}

                        <p class="bs-component">
                            <table>
                                <tr>
                                    <td>{{ form.username.label_tag }}</td>
                                    <td>{{ form.username }}</td>
                                </tr>
                                <tr>
                                    <td>{{ form.password.label_tag }}</td>
                                    <td>{{ form.password }}</td>
                                </tr>
                            </table>
                        </p>
                        <p class="bs-component">
                            <center>
                                <input class="btn btn-success btn-sm" type="submit" value="login" />
                            </center>
                        </p>
                        <input type="hidden" name="next" value="{{ next }}" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}


<script>
{% if not user.is_authenticated %}
$("ul.nav.navbar-nav.navbar-right").css("display","none");
{% endif %}
</script>

{% endblock %}

notes/templates/notes/movie_form.html
{% extends 'notes/base.html' %}
{% block body %}
    <h2>New Note</h2>
    <form  action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'notes/form-template.html' %}
        <br><br><br><br><br>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
{% endblock %}

notes/templates/notes/movie_list.html

{% extends 'notes/base.html' %}

{% block body %}
    <h3>Movies</h3>
   <ul>
        {% for m in all_movies %}
            <li>
                <h4> {{ m.name }}</h4>
            <p>Release date: {{ m.release_date }}</p>
            <p><a href="{{ m.imdb_link }}">Imdb Link</a></p> </li>
            <h5>Categories: </h5>
            {% for cat in m.categories.all %}
            <li>{{ cat.name }}</li>
            {% endfor %}
            <form action="{% url 'notes:movie-update' m.id %}" method="post" style="display: inline">
              {% csrf_token %}
              <input type="hidden" name="album_id" value="{{ album.id }}">
              <button type="submit" class="btn btn-default btn-sm">
                  <span class="glyphicon">Update</span>
              </button>
          </form>
            <br><br>
        {% endfor %}

    </ul>
{% endblock %}

notes/templates/notes/note_form.html
{% extends 'notes/base.html' %}
{% block body %}
    <h2>New Note</h2>
    <form  action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'notes/form-template.html' %}
        <br><br><br><br><br>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
{% endblock %}

notes/templates/notes/note_list.html

{% extends 'notes/base.html' %}

{% block body %}
    <h3>Notes</h3>
   <ul>
        {% for m in all_notes %}
            <li>
                <h4>{{ m.title }}</h4>
                <p>{{ m.body }}</p>
                <p>Created at: "{{ m.created_at }}"</p> </li><br>

        {% endfor %}

    </ul>
{% endblock %}